// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_dodge5 = new UnifiedAchievement("Dodge5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIx-rq2fAREAIQAg"
#else
            "Dodge5"
#endif
            );

        public static UnifiedAchievement Dodge5
        {
            get { return s_dodge5; }
        }

        private static readonly UnifiedAchievement s_dodge15 = new UnifiedAchievement("Dodge15",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIx-rq2fAREAIQAw"
#else
            "Dodge15"
#endif
            );

        public static UnifiedAchievement Dodge15
        {
            get { return s_dodge15; }
        }

        private static readonly UnifiedAchievement s_dodge30 = new UnifiedAchievement("Dodge30",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIx-rq2fAREAIQBA"
#else
            "Dodge30"
#endif
            );

        public static UnifiedAchievement Dodge30
        {
            get { return s_dodge30; }
        }

        private static readonly UnifiedAchievement s_dodge50 = new UnifiedAchievement("Dodge50",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIx-rq2fAREAIQBQ"
#else
            "Dodge50"
#endif
            );

        public static UnifiedAchievement Dodge50
        {
            get { return s_dodge50; }
        }

        private static readonly UnifiedAchievement s_dodge100 = new UnifiedAchievement("Dodge100",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIx-rq2fAREAIQBg"
#else
            "Dodge100"
#endif
            );

        public static UnifiedAchievement Dodge100
        {
            get { return s_dodge100; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_dodge5,
            s_dodge15,
            s_dodge30,
            s_dodge50,
            s_dodge100,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Dodge5", s_dodge5 },
            { "Dodge15", s_dodge15 },
            { "Dodge30", s_dodge30 },
            { "Dodge50", s_dodge50 },
            { "Dodge100", s_dodge100 },
        };
    }
}
